language: bash

# for secret experimental features ;)
sudo: 9000

before_script:
  - env | sort

script:
  - make boot2docker-base.iso boot2docker-docker.iso
  - make all -j$(nproc)

# vim:set et ts=2 sw=2:
